# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ig_vp4-xQqw3FVxDkzMrBNaZstwANaQF
"""

!pip install BTrees
from BTrees.IIBTree import IIBTree
import time

t = IIBTree()
insertTimeS = time.time()
for i in range(1000):
    t.update({i:2*i})
insertTimeE = time.time()
print(f'The time take is {round((insertTimeE-insertTimeS)*1000,3)} ms')
key = int(input('Enter the key : '))
searchTimeS = time.time()
if t.has_key(key):
    print(t[key])
searchTimeE = time.time()
print(f'The time take is {round((searchTimeE-searchTimeS)*1000,3)} ms')

!pip install bplustree
from bplustree import BPlusTree
import time

tree = BPlusTree('./tree.db',order=50)
for i in range(1000):
    data = (i*2).to_bytes(10,'big')
    tree[i] = data
key = int(input("Enter the key : "))
start = time.time()
byteData = tree.get(key)
end = time.time()
intdata = int.from_bytes(byteData,'big')
print("Value : ",intdata)
print("Time taken : ",(end-start)*1000," ms")